# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'tsog-alphabet-mobile' do
  pod 'PDKeychainBindingsController'
  pod 'Analytics'
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'tsog-alphabet-desktop' do

end

