var res = {
   // Config
   Forest_Config_JSON: "config/forest_config.json",
   Game_Config_JSON: "config/game_config.json",
   Room_Config_JSON: "config/room_config.json",

   //font
   RedFont_png: "red-font-export.png",
   YellowFont_png: "yellow-font-export.png",
   PurpleFont_png: "purple-font-export.png",
   GreenFont_png: "green-font-export.png",
   RedFont_fnt: "red-font-export.fnt",
   YellowFont_fnt: "yellow-font-export.fnt",
   PurpleFont_fnt: "purple-font-export.fnt",
   GreenFont_fnt: "green-font-export.fnt",

   forest_jpg : "res/forest.jpg",
   room_jpg: "Bedroom-screen.jpg",
   room_roof_png: "bedroom-roof.png",
   room_clock_png: "bedroom-clock.png",
   room_ribbon_png: "bedroom-ribbon.png",
   room_window_png: "bedroom-window.png",

   GrayButton_png: "res/gray-button.png",
   Red_PlaceHolder_jpg: "res/red-place-holder.jpg",
   Button_Refresh_png: "res/refresh-button.png",
   Back_Button_png: "res/back.png",
   Back_Button_Pressed_png: "res/back-pressed.png",
   BG_jpg: "BG.jpg",

   // plist file
   Forest_plist: "forest.plist",
   Forest_png: "forest.png",

   // Animals
   Ant_png: "animals/ant.png",
   Fish_png: "animals/fish.png",
   Bear_png: "animals/bear.png",
   Bee_png: "animals/bee.png",
   Bird_png: "animals/bird.png",
   Cat_png: "animals/cat.png",
   Cow_png: "animals/cow.png",
   Duck_png: "animals/duck.png",
   Elephant_png: "animals/elephant.png",
   Horse_png: "animals/horse.png",
   Insect_png: "animals/insect.png",
   Lion_png: "animals/lion.png",
   Monkey_png: "animals/monkey.png",
   Frog_png: "animals/frog.png",
   Owl_ong:"animals/owl.png",
   Tiger_png: "animals/tiger.png",
   Rat_png: "animals/rat.png",
   Panda_png: "animals/panda.mp3",
   Nest_png: "animals/nest.png",

   // Things
   Map_png: "things/map.png",
   Grap_png: "things/grape.png",
   Watch_png: "things/watch.png",
   Desk_png: "things/desk.png",
   Duster_png: "things/duster.png",
   Jar_jpg: "things/jar.png",
   Hat_jpg: "things/hat.png",
   Lamp_jpg: "things/lamp.png",
   Apple_png: "things/apple.png",
   Banana_png: "things/banana.png",
   Book_png: "things/book.png",
   Chair_png: "things/chair.png",
   Pencils_png: "things/pencils.png",
   Egg_png: "things/egg.png",
   Potato_png: "things/potato.png",
   Towel_png: "things/towel.png",
   Umbrella_png: "things/umbrella.png",
   Key_png:"things/key.png",
   Sock_png: "things/sock.png",
   Joker_png: "things/joker.png",
   Kite_png: "things/kite.png",
   Strawberry_png: "things/strawberry.png",
   Pen_png: "things/pen.png",
   Table_png: "things/table.png",

   // Hud
   Hud_plist: "hud/hud.plist",
   Hud_png: "hud/hud.png",
   Hud_progress_bar_png: "hud/progress-bar.jpg",
   Hud_progress_bar_alpha_png: "hud/progress-bar-alpha.jpg",
   HudFont_fnt: "hud-font-export.fnt",
   HudFont_png: "hud-font.png",

   // Shader
   SpriteDistort_fsh: "res/shader/SpriteDistort.fsh",
   SolidColor_fsh: "res/shader/SolidColor.fsh",
   ScrollingTexture_fsh: "res/shader/ScrollingTexture.fsh",
   PositionTextureColor_vsh: "res/shader/PositionTextureColor.vsh",
   PositionTextureColor_noMVP_vsh: "res/shader/PositionTextureColor_noMVP.vsh",

   // Effect
   Smoke_effect_plist: "effect-smoke.plist",
   Smoke_effect_png: "effect-smoke.png",
   Sparkle_effect_png: "sparkle-effect.png",
   Sparkle_effect_plist: "sparkle-effect.plist",

   // Smoke_sound: "res/smoke-sound.mp3"

   // Sound effect
   DROP_mp3: "sounds/drop.mp3",
   PICKUP_mp3: "sounds/pickup.mp3",
   SMOKE_mp3: "sounds/smoke.mp3",


   // Animal Sound
   ANT_mp3: "sounds/animals/ant.mp3",
   BEAR_mp3: "sounds/animals/bear.mp3",
   BEE_mp3: "sounds/animals/bee.mp3",
   BIRD_mp3: "sounds/animals/bird.mp3",
   CAT_mp3: "sounds/animals/cat.mp3",
   COW_mp3: "sounds/animals/cow.mp3",
   DOG_mp3: "sounds/animals/dog.mp3",
   DUCK_mp3: "sounds/animals/duck.mp3",
   ELEPHANT_mp3: "sounds/animals/elephant.mp3",
   FISH_mp3: "sounds/animals/fish.mp3",
   FROG_mp3: "sounds/animals/frog.mp3",
   HORSE_mp3: "sounds/animals/horse.mp3",
   INSECT_mp3: "sounds/animals/insect.mp3",
   LION_mp3: "sounds/animals/lion.mp3",
   MONKEY_mp3: "sounds/animals/monkey.mp3",
   NEST_mp3: "sounds/animals/nest.mp3",
   OWL_mp3: "sounds/animals/owl.mp3",
   PANDA_mp3: "sounds/animals/panda.mp3",
   RAT_mp3: "sounds/animals/rat.mp3",
   TIGER_mp3: "sounds/animals/tiger.mp3",
   ZEBRA_mp3: "sounds/animals/zebra.mp3",

   // Things sound
   APPLE_1_mp3: "res/sounds/things/apple-1.mp3",
   APPLE_2_mp3: "res/sounds/things/apple-2.mp3",
   BANANA_1_mp3: "res/sounds/things/banana-1.mp3",
   BANANA_2_mp3: "res/sounds/things/banana-2.mp3",
   BOOK_1_mp3: "res/sounds/things/book-1.mp3",
   BOOK_2_mp3: "res/sounds/things/book-2.mp3",
   CHAIR_1_mp3: "res/sounds/things/chair-1.mp3",
   CHAIR_2_mp3: "res/sounds/things/chair-2.mp3",
   PENCILS_1_mp3: "res/sounds/things/pencils-1.mp3",
   PENCILS_2_mp3: "res/sounds/things/pencils-2.mp3",
   DESK_1_mp3: "res/sounds/things/desk-1.mp3",
   DESK_2_mp3: "res/sounds/things/desk-2.mp3",
   DUSTER_1_mp3: "res/sounds/things/duster-1.mp3",
   DUSTER_2_mp3: "res/sounds/things/duster-2.mp3",
   EGG_1_mp3: "res/sounds/things/egg-1.mp3",
   EGG_2_mp3: "res/sounds/things/egg-2.mp3",
   GRAPE_1_mp3: "res/sounds/things/grape-1.mp3",
   GRAPE_2_mp3: "res/sounds/things/grape-2.mp3",
   HAT_1_mp3: "res/sounds/things/hat-1.mp3",
   HAT_2_mp3: "res/sounds/things/hat-2.mp3",
   JAR_1_mp3: "res/sounds/things/jar-1.mp3",
   JAR_2_mp3: "res/sounds/things/jar-2.mp3",
   JOKER_1_mp3: "res/sounds/things/joker-1.mp3",
   JOKER_2_mp3: "res/sounds/things/joker-2.mp3",
   KITE_1_mp3: "res/sounds/things/kite-1.mp3",
   KITE_2_mp3: "res/sounds/things/kite-2.mp3",
   LAMP_1_mp3: "res/sounds/things/lamp-1.mp3",
   LAMP_2_mp3: "res/sounds/things/lamp-2.mp3",
   MAP_1_mp3: "res/sounds/things/map-1.mp3",
   MAP_2_mp3: "res/sounds/things/map-2.mp3",
   ORANGE_1_mp3: "res/sounds/things/orange-1.mp3",
   ORANGE_2_mp3: "res/sounds/things/orange-2.mp3",
   POTATO_1_mp3: "res/sounds/things/potato-1.mp3",
   POTATO_2_mp3: "res/sounds/things/potato-2.mp3",
   TOWEL_1_mp3: "res/sounds/things/towel-1.mp3",
   TOWEL_2_mp3: "res/sounds/things/towel-2.mp3",
   UMBRELLA_1_mp3: "res/sounds/things/umbrella-1.mp3",
   UMBRELLA_2_mp3: "res/sounds/things/umbrella-2.mp3",
   VEST_1_mp3: "res/sounds/things/vest-1.mp3",
   VEST_2_mp3: "res/sounds/things/vest-2.mp3",
   WATCH_1_mp3: "res/sounds/things/watch-1.mp3",
   WATCH_2_mp3: "res/sounds/things/watch-2.mp3",
   KEY_1_mp3:"res/sounds/things/key-1.mp3",
   KEY_2_mp3:"res/sounds/things/key-2.mp3",
   JOCKER_1_mp3:"res/sounds/things/jocker-1.mp3",
   JOCKER_2_mp3: "res/sounds/things/jocker-2.mp3",
   SOCK_1_mp3: "res/sounds/things/sock-1.mp3",
   SOCK_2_mp3: "res/sounds/things/sock-2.mp3",
   STRAWBERRY_1_mp3: "res/sounds/things/strawberry-1.mp3",
   STRAWBERRY_2_mp3: "res/sounds/things/strawberry-2.mp3",
   PEN_1_mp3: "res/sounds/things/pen-1.mp3",
   PEN_2_mp3: "res/sounds/things/pen-2.mp3",
   //countdown
   COUNTDOWN_mp3 : "res/sounds/Countdown.mp3",
   
   // BG sound 
   BACKGROUND_mp3: "sounds/background.mp3",


};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}